# Generated by Django 4.2.5 on 2023-10-06 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_product_imgfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='imgfile',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='상품이미지'),
        ),
    ]
